# 声纹识别API Docker Compose配置

version: '3.8'

services:
  voiceprint-api:
    build:
      context: .
      dockerfile: Dockerfile
    image: voiceprint-api:latest
    container_name: voiceprint-api
    restart: unless-stopped
    ports:
      - "8005:8005"
    environment:
      - TZ=Asia/Shanghai
      - PYTHONUNBUFFERED=1
    volumes:
      # 数据持久化
      - ./data:/app/data
      # 日志持久化（可选）
      - ./logs:/app/logs
    healthcheck:
      test: ["CMD", "python", "-c", "import urllib.request; urllib.request.urlopen('http://localhost:8005/voiceprint/health')"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s
    networks:
      - voiceprint-net
    deploy:
      resources:
        limits:
          cpus: '2'
          memory: 2G
        reservations:
          cpus: '1'
          memory: 1G

networks:
  voiceprint-net:
    driver: bridge
